language: python
git:
  depth: 9999
python:
- '3.6'
sudo: false
cache:
  directories:
  - "$HOME/.cache/pip"
addons:
  apt:
    packages:
    - libhdf5-serial-dev
    - libnetcdf-dev
    - libproj-dev
    - libgdal1-dev
    - libudunits2-dev
    - libblas-dev
    - liblapack-dev
    - gfortran
install:
- export CPLUS_INCLUDE_PATH="/usr/include/gdal"
- export C_INCLUDE_PATH="/usr/include/gdal"
- travis_retry pip install --upgrade pip
- travis_retry pip install --upgrade pytest pytest-cov pytest-flake8 deepdiff flake8 pep8-naming
- travis_retry pip install gdal==1.10.0 rasterio shapely pyyaml click ciso8601 checksumdir
- pip freeze
script:
- pytest
before_deploy:
- python setup.py sdist
deploy:
  provider: releases
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^tesp-[0-9]+\\.[0-9]+\\.[0-9]+$"
    repo: OpenDataCubePipelines/tesp
  api-key:
    secure: FPFqSBFWEJsPx/VKl5Bku9iF55kqrGr27fmgTkSw2mT3VBdtjWZeMc0N92xN1LAT2ObzOPnix2KFL48d3pnYhcVNFnkor78JeiTN+20294KBWqbAzX/WEJUnttdaXunxalNbd+GlermA+gybI42+u3bD6LYM2mQIm3/XN6m1x2Wc0XisqGAnVXgqazI05G0XHWxr7GRGo2YFWXNet1F2px/yvwpcHdajZscLbmAUVGTfOxZsZVCFy+qm2IYS4C3hKlSnpRO3UDJQlbNdQU+nBfJIj/GPtpx+SD44L0En5QMuWanGCZp6I1/J+vZYgbe7zs3/F2vVHbwqSRYLOeWJIk/hxPGiY500RbE21eTIxti7io6dF7p2pmjXYsDFy4HnxS+46mboh25WoAGjHjtBMSFfPGZgjH1wpnBFTh54rc9K1d39SQi5ObKqvrqowv7w9UvvCyfQqyVI9McXcWPOZ2JCDABsE5oHoDZgjd28EfAgDctZgq3doARp5el066aSU4y+q/pvU9Z8kLvXegYjO0lqdL423c5slWfH8HqA0zaPaSfOhZH1ncc/x9OFEX97jY+Aq0a5vUaBxOxxkEz0VBJYoE1x7J47vgHJcVld0yOTgobWR0PQVSksjcz5Q+YJbmWq0dpxIO8JrftN22eyD3Nage+BWxAzOld4t4M7gj4=
